use crate::{
    frontend::gir::GirWorldV1, frontend::hir::Validated, frontend::mono::MonoWorldV1,
    target::TargetName,
};

#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct BackendPlan {
    pub(crate) target: TargetName,
    pub(crate) entry: String,
    pub(crate) function_count: u32,
    pub(crate) semantic_fingerprint: [u8; 32],
    pub(crate) runtime_checks_elided_count: u32,
    pub(crate) mono_instance_count: u32,
    pub(crate) mono_root_count: u32,
    pub(crate) mono_graph_fingerprint: [u8; 32],
    pub(crate) type_id_count: u32,
    pub(crate) type_universe_fingerprint: [u8; 32],
    pub(crate) late_constant_count: u32,
    pub(crate) late_constants_fingerprint: [u8; 32],
    pub(crate) gir_body_count: u32,
    pub(crate) gir_block_count: u32,
    pub(crate) gir_statement_count: u32,
    pub(crate) gir_fingerprint: [u8; 32],
    pub(crate) placement_count: u32,
    pub(crate) turn_region_count: u32,
    pub(crate) local_heap_count: u32,
    pub(crate) shared_heap_count: u32,
    pub(crate) placement_fingerprint: [u8; 32],
    pub(crate) lir_body_count: u32,
    pub(crate) lir_block_count: u32,
    pub(crate) lir_instruction_count: u32,
    pub(crate) lir_memory_operation_count: u32,
    pub(crate) lir_safepoint_count: u32,
    pub(crate) lir_fingerprint: [u8; 32],
    pub(crate) optimization_revision: u32,
    pub(crate) poll_budget: u32,
    pub(crate) poll_count: u32,
    pub(crate) poll_free_leaf_count: u32,
    pub(crate) poll_summary_fingerprint: [u8; 32],
    pub(crate) raw_size_class_count: u32,
    pub(crate) raw_shard_count: u32,
    pub(crate) raw_batch_max_items: u32,
    pub(crate) raw_batch_soft_bytes: u64,
    pub(crate) raw_message_node_capacity: u32,
    pub(crate) raw_model_fingerprint: [u8; 32],
    pub(crate) coroutine_runtime: crate::runtime::CoroutineRuntimeContract,
    pub(crate) scheduler_local_capacity: u32,
    pub(crate) scheduler_remote_shard_count: u32,
    pub(crate) scheduler_batch_max_items: u32,
    pub(crate) scheduler_service_interval: u32,
    pub(crate) scheduler_service_batch: u32,
    pub(crate) scheduler_contract_fingerprint: [u8; 32],
    pub(crate) scheduler_runtime: crate::runtime::SchedulerRuntimeContract,
    pub(crate) wait_inline_select_cases: u32,
    pub(crate) wait_scratch_class_count: u32,
    pub(crate) wait_node_class_count: u32,
    pub(crate) wait_contract_fingerprint: [u8; 32],
    pub(crate) wait_demand: crate::runtime::WaitDemand,
    pub(crate) wait_runtime: crate::runtime::WaitRuntimeContract,
    pub(crate) sync_contract_fingerprint: [u8; 32],
    pub(crate) sync_demand: crate::runtime::SyncDemand,
    pub(crate) sync_primitive_count: u32,
    pub(crate) sync_runtime: crate::runtime::SyncRuntimeContract,
    pub(crate) stackmap_function_count: u32,
    pub(crate) stackmap_safepoint_count: u32,
    pub(crate) stackmap_map_count: u32,
    pub(crate) stackmap_root_words: u32,
    pub(crate) stackmap_contract_fingerprint: [u8; 32],
    pub(crate) stackmap_demand: crate::runtime::StackMapDemand,
    pub(crate) gc_metadata_type_count: u32,
    pub(crate) gc_metadata_trace_bytes: u32,
    pub(crate) gc_metadata_value_bytes: u32,
    pub(crate) gc_metadata_vtable_count: u32,
    pub(crate) gc_metadata_root_count: u32,
    pub(crate) gc_metadata_arena_bytes: u64,
    pub(crate) gc_metadata_block_bytes: u32,
    pub(crate) gc_metadata_line_bytes: u32,
    pub(crate) gc_metadata_contract_fingerprint: [u8; 32],
    pub(crate) gc_metadata_demand: crate::runtime::GcMetadataDemand,
    pub(crate) gc_type_section: Vec<u8>,
    pub(crate) gc_metadata_section: Vec<u8>,
    pub(crate) barrier_contract_fingerprint: [u8; 32],
    pub(crate) barrier_demand: crate::runtime::BarrierDemand,
    pub(crate) barrier_card_granularity_bytes: u32,
    pub(crate) barrier_card_mark_buffer_entries: u32,
    pub(crate) barrier_card_mark_stamp_entries: u32,
    pub(crate) barrier_flush_reason_count: u32,
    pub(crate) barrier_card_mark_batch_fields: u32,
    pub(crate) barrier_record_count: u32,
    pub(crate) barrier_runtime: crate::runtime::BarrierRuntimeContract,
    pub(crate) pacing_contract_fingerprint: [u8; 32],
    pub(crate) pacing_profile: String,
    pub(crate) pacing_profile_revision: u32,
    pub(crate) pacing_min_growth_budget: u64,
    pub(crate) pacing_assist_threshold: u64,
    pub(crate) pacing_assist_quantum: u64,
    pub(crate) pacing_mark_cost_per_byte: u32,
    pub(crate) pacing_gc_cpu_fraction: u32,
    pub(crate) pacing_gc_cpu_window_cost: u64,
    pub(crate) pacing_remark_cost_budget: u64,
    pub(crate) pacing_evacuation_pause_bytes: u64,
    pub(crate) pacing_evacuation_pause_roots: u32,
    pub(crate) pacing_evacuation_pause_fields: u32,
    pub(crate) pacing_pressure_enter_ratio: u32,
    pub(crate) pacing_pressure_clear_ratio: u32,
    pub(crate) pacing_credit_source_count: u32,
    pub(crate) turn_region_sites: u32,
    pub(crate) turn_region_publish_sites: u32,
    pub(crate) turn_region_reset_sites: u32,
    pub(crate) turn_region_promote_sites: u32,
    pub(crate) turn_region_transfer_sites: u32,
    pub(crate) turn_region_capacity_class_count: u32,
    pub(crate) turn_region_object_limit: u32,
    pub(crate) turn_region_max_bytes: u64,
    pub(crate) turn_region_total_bytes: u64,
    pub(crate) turn_region_contract_fingerprint: [u8; 32],
    pub(crate) turn_region_demand: crate::runtime::TurnRegionDemand,
    pub(crate) turn_region_runtime: crate::runtime::TurnRegionRuntimeContract,
    pub(crate) pacing_demand: crate::runtime::GcPacingDemand,
    pub(crate) pacing_runtime: crate::runtime::GcPacingRuntimeContract,
    pub(crate) resource_cell_header_bytes: u32,
    pub(crate) resource_class_count: u32,
    pub(crate) resource_kind_count: u32,
    pub(crate) release_descriptor_count: u32,
    pub(crate) resource_sites: u32,
    pub(crate) release_sites: u32,
    pub(crate) platform_profile: String,
    pub(crate) platform_op_count: u32,
    pub(crate) platform_range_class_count: u32,
    pub(crate) platform_contract_fingerprint: [u8; 32],
    pub(crate) platform_demand: super::runtime::PlatformRangeDemand,
    pub(crate) ledger_category_count: u32,
}

pub(crate) fn plan(
    target: TargetName,
    hir: &Validated,
    mono: &MonoWorldV1,
    gir: &GirWorldV1,
    lir: &crate::lir::Validated,
    raw: &crate::runtime::RuntimeRawContractV1,
    runtime_checks_elided_count: u32,
) -> Option<BackendPlan> {
    let module = hir.module();
    let entry = module.entry?;
    let placement = gir.placement.counts();
    Some(BackendPlan {
        target,
        entry: module.definitions[entry.index()].name.clone(),
        function_count: mono.instances.len() as u32,
        semantic_fingerprint: hir.fingerprint(),
        runtime_checks_elided_count,
        mono_instance_count: mono.instances.len() as u32,
        mono_root_count: mono.roots.len() as u32,
        mono_graph_fingerprint: mono.graph_fingerprint,
        type_id_count: mono.universe.records.len() as u32,
        type_universe_fingerprint: mono.universe.fingerprint,
        late_constant_count: mono.late.results.len() as u32,
        late_constants_fingerprint: mono.late.fingerprint,
        gir_body_count: gir.bodies.len() as u32,
        gir_block_count: gir.bodies.iter().map(|body| body.blocks.len() as u32).sum(),
        gir_statement_count: gir
            .bodies
            .iter()
            .map(|body| body.statements.len() as u32)
            .sum(),
        gir_fingerprint: gir.fingerprint,
        placement_count: placement.total,
        turn_region_count: placement.turn_region,
        local_heap_count: placement.local_heap,
        shared_heap_count: placement.shared_heap,
        placement_fingerprint: gir.placement.fingerprint,
        lir_body_count: u32::try_from(lir.bodies()).expect("LIR body 数量适配 u32"),
        lir_block_count: u32::try_from(lir.blocks()).expect("LIR block 数量适配 u32"),
        lir_instruction_count: u32::try_from(lir.instructions()).expect("LIR 指令数量适配 u32"),
        lir_memory_operation_count: u32::try_from(lir.memory_operations())
            .expect("LIR Mem 数量适配 u32"),
        lir_safepoint_count: u32::try_from(lir.safepoints()).expect("LIR safepoint 数量适配 u32"),
        lir_fingerprint: lir.fingerprint(),
        optimization_revision: lir.optimization_revision(),
        poll_budget: lir.poll_budget(),
        poll_count: u32::try_from(lir.poll_count()).expect("poll 数量适配 u32"),
        poll_free_leaf_count: u32::try_from(lir.poll_free_leaf_count())
            .expect("poll-free 叶数量适配 u32"),
        poll_summary_fingerprint: lir.poll_summary_fingerprint(),
        raw_size_class_count: raw.class_count(),
        raw_shard_count: raw.shard_count(),
        raw_batch_max_items: raw.batch_limits().items,
        raw_batch_soft_bytes: raw.batch_limits().batch_soft_bytes,
        raw_message_node_capacity: raw.message_node_capacity(),
        raw_model_fingerprint: raw.fingerprint(),
        coroutine_runtime: raw.coroutine().clone(),
        scheduler_local_capacity: raw.scheduler().local_capacity(),
        scheduler_remote_shard_count: raw.scheduler().remote_shards(),
        scheduler_batch_max_items: raw.scheduler().batch_max(),
        scheduler_service_interval: raw.scheduler().service_interval(),
        scheduler_service_batch: raw.scheduler().service_batch(),
        scheduler_contract_fingerprint: raw.scheduler().fingerprint(),
        scheduler_runtime: raw.scheduler().clone(),
        wait_inline_select_cases: raw.wait().inline_select_cases(),
        wait_scratch_class_count: raw.wait().scratch_class_count(),
        wait_node_class_count: raw.wait().wait_node_class_count(),
        wait_contract_fingerprint: raw.wait().fingerprint(),
        wait_demand: raw.wait().demand,
        wait_runtime: raw.wait().clone(),
        sync_contract_fingerprint: raw.sync().fingerprint(),
        sync_demand: raw.sync().demand,
        sync_primitive_count: raw.sync().primitive_count(),
        sync_runtime: raw.sync().clone(),
        stackmap_function_count: raw.stackmap().demand().functions,
        stackmap_safepoint_count: raw.stackmap().demand().safepoints,
        stackmap_map_count: raw.stackmap().demand().maps,
        stackmap_root_words: raw.stackmap().demand().root_words,
        stackmap_contract_fingerprint: raw.stackmap().fingerprint,
        stackmap_demand: raw.stackmap().demand(),
        gc_metadata_type_count: raw.gc_metadata().demand.type_count,
        gc_metadata_trace_bytes: raw.gc_metadata().demand.trace_program_bytes,
        gc_metadata_value_bytes: raw.gc_metadata().demand.value_program_bytes,
        gc_metadata_vtable_count: raw.gc_metadata().demand.vtable_count,
        gc_metadata_root_count: raw.gc_metadata().demand.root_range_count,
        gc_metadata_arena_bytes: raw.gc_metadata().arena_bytes,
        gc_metadata_block_bytes: raw.gc_metadata().block_bytes,
        gc_metadata_line_bytes: raw.gc_metadata().line_bytes,
        gc_metadata_contract_fingerprint: raw.gc_metadata().fingerprint,
        gc_metadata_demand: raw.gc_metadata().demand,
        gc_type_section: raw.gc_metadata().type_section.clone(),
        gc_metadata_section: raw.gc_metadata().metadata_section.clone(),
        barrier_contract_fingerprint: raw.barrier().fingerprint(),
        barrier_demand: raw.barrier().demand(),
        barrier_card_granularity_bytes: raw.barrier().card_granularity_bytes(),
        barrier_card_mark_buffer_entries: raw.barrier().card_mark_buffer_entries(),
        barrier_card_mark_stamp_entries: raw.barrier().card_mark_stamp_entries(),
        barrier_flush_reason_count: raw.barrier().flush_reason_count(),
        barrier_card_mark_batch_fields: raw.barrier().card_mark_batch_field_count(),
        barrier_record_count: raw.barrier().record_count(),
        barrier_runtime: raw.barrier().clone(),
        pacing_contract_fingerprint: raw.pacing().fingerprint(),
        pacing_profile: raw.pacing().profile().to_owned(),
        pacing_profile_revision: raw.pacing().profile_revision(),
        pacing_min_growth_budget: raw.pacing().min_growth_budget(),
        pacing_assist_threshold: raw.pacing().assist_threshold(),
        pacing_assist_quantum: raw.pacing().assist_quantum(),
        pacing_mark_cost_per_byte: raw.pacing().mark_cost_per_byte(),
        pacing_gc_cpu_fraction: raw.pacing().gc_cpu_fraction(),
        pacing_gc_cpu_window_cost: raw.pacing().gc_cpu_window_cost(),
        pacing_remark_cost_budget: raw.pacing().remark_cost_budget(),
        pacing_evacuation_pause_bytes: raw.pacing().evacuation_pause_bytes(),
        pacing_evacuation_pause_roots: raw.pacing().evacuation_pause_roots(),
        pacing_evacuation_pause_fields: raw.pacing().evacuation_pause_fields(),
        pacing_pressure_enter_ratio: raw.pacing().pressure_enter_ratio(),
        pacing_pressure_clear_ratio: raw.pacing().pressure_clear_ratio(),
        pacing_credit_source_count: raw.pacing().credit_sources.len() as u32,
        pacing_demand: raw.pacing().demand(),
        pacing_runtime: raw.pacing().clone(),
        turn_region_sites: raw.region().demand().regions,
        turn_region_publish_sites: raw.region().demand().publish_sites,
        turn_region_reset_sites: raw.region().demand().reset_sites,
        turn_region_promote_sites: raw.region().demand().promote_sites,
        turn_region_transfer_sites: raw.region().demand().transfer_sites,
        turn_region_capacity_class_count: raw.region().capacity_class_count(),
        turn_region_object_limit: raw.region().object_limit(),
        turn_region_max_bytes: raw.region().demand().max_region_bytes,
        turn_region_total_bytes: raw.region().demand().total_bytes,
        turn_region_contract_fingerprint: raw.region().fingerprint(),
        turn_region_demand: raw.region().demand(),
        turn_region_runtime: raw.region().clone(),
        resource_cell_header_bytes: raw.resources().header.header_bytes,
        resource_class_count: raw.resource_class_count(),
        resource_kind_count: raw.resource_kind_count(),
        release_descriptor_count: raw.resources().release.fields.len() as u32,
        resource_sites: raw.resource_demand().resource_sites,
        release_sites: raw.resource_demand().release_sites,
        platform_profile: raw.platform().profile().to_owned(),
        platform_op_count: raw.platform().op_count(),
        platform_range_class_count: raw.platform().class_count(),
        platform_contract_fingerprint: *blake3::Hasher::new_derive_key("gugu-platform-range-v1")
            .update(&raw.platform().canonical_bytes())
            .finalize()
            .as_bytes(),
        platform_demand: *raw.platform_demand(),
        ledger_category_count: raw.ledger_categories().len() as u32,
    })
}
