use crate::{
    frontend::gir::GirWorldV1, frontend::hir::Validated, frontend::mono::MonoWorldV1,
    target::TargetName,
};

#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct BackendPlan {
    pub(crate) target: TargetName,
    pub(crate) entry: String,
    pub(crate) function_count: u32,
    pub(crate) semantic_fingerprint: [u8; 32],
    pub(crate) runtime_checks_elided_count: u32,
    pub(crate) mono_instance_count: u32,
    pub(crate) mono_root_count: u32,
    pub(crate) mono_graph_fingerprint: [u8; 32],
    pub(crate) type_id_count: u32,
    pub(crate) type_universe_fingerprint: [u8; 32],
    pub(crate) late_constant_count: u32,
    pub(crate) late_constants_fingerprint: [u8; 32],
    pub(crate) gir_body_count: u32,
    pub(crate) gir_block_count: u32,
    pub(crate) gir_statement_count: u32,
    pub(crate) gir_fingerprint: [u8; 32],
    pub(crate) placement_count: u32,
    pub(crate) turn_region_count: u32,
    pub(crate) local_heap_count: u32,
    pub(crate) shared_heap_count: u32,
    pub(crate) placement_fingerprint: [u8; 32],
    pub(crate) lir_body_count: u32,
    pub(crate) lir_block_count: u32,
    pub(crate) lir_instruction_count: u32,
    pub(crate) lir_memory_operation_count: u32,
    pub(crate) lir_safepoint_count: u32,
    pub(crate) lir_fingerprint: [u8; 32],
    pub(crate) optimization_revision: u32,
    pub(crate) poll_budget: u32,
    pub(crate) poll_count: u32,
    pub(crate) poll_free_leaf_count: u32,
    pub(crate) poll_summary_fingerprint: [u8; 32],
    pub(crate) raw_size_class_count: u32,
    pub(crate) raw_shard_count: u32,
    pub(crate) raw_batch_max_items: u32,
    pub(crate) raw_batch_soft_bytes: u64,
    pub(crate) raw_message_node_capacity: u32,
    pub(crate) raw_model_fingerprint: [u8; 32],
    pub(crate) coroutine_runtime: crate::runtime::CoroutineRuntimeContract,
    pub(crate) resource_cell_header_bytes: u32,
    pub(crate) resource_class_count: u32,
    pub(crate) resource_kind_count: u32,
    pub(crate) release_descriptor_count: u32,
    pub(crate) resource_sites: u32,
    pub(crate) release_sites: u32,
    pub(crate) platform_profile: String,
    pub(crate) platform_op_count: u32,
    pub(crate) platform_range_class_count: u32,
    pub(crate) platform_contract_fingerprint: [u8; 32],
    pub(crate) platform_demand: super::runtime::PlatformRangeDemand,
    pub(crate) ledger_category_count: u32,
}

pub(crate) fn plan(
    target: TargetName,
    hir: &Validated,
    mono: &MonoWorldV1,
    gir: &GirWorldV1,
    lir: &crate::lir::Validated,
    raw: &crate::runtime::RuntimeRawContractV1,
    runtime_checks_elided_count: u32,
) -> Option<BackendPlan> {
    let module = hir.module();
    let entry = module.entry?;
    let placement = gir.placement.counts();
    Some(BackendPlan {
        target,
        entry: module.definitions[entry.index()].name.clone(),
        function_count: mono.instances.len() as u32,
        semantic_fingerprint: hir.fingerprint(),
        runtime_checks_elided_count,
        mono_instance_count: mono.instances.len() as u32,
        mono_root_count: mono.roots.len() as u32,
        mono_graph_fingerprint: mono.graph_fingerprint,
        type_id_count: mono.universe.records.len() as u32,
        type_universe_fingerprint: mono.universe.fingerprint,
        late_constant_count: mono.late.results.len() as u32,
        late_constants_fingerprint: mono.late.fingerprint,
        gir_body_count: gir.bodies.len() as u32,
        gir_block_count: gir.bodies.iter().map(|body| body.blocks.len() as u32).sum(),
        gir_statement_count: gir
            .bodies
            .iter()
            .map(|body| body.statements.len() as u32)
            .sum(),
        gir_fingerprint: gir.fingerprint,
        placement_count: placement.total,
        turn_region_count: placement.turn_region,
        local_heap_count: placement.local_heap,
        shared_heap_count: placement.shared_heap,
        placement_fingerprint: gir.placement.fingerprint,
        lir_body_count: u32::try_from(lir.bodies()).expect("LIR body 数量适配 u32"),
        lir_block_count: u32::try_from(lir.blocks()).expect("LIR block 数量适配 u32"),
        lir_instruction_count: u32::try_from(lir.instructions()).expect("LIR 指令数量适配 u32"),
        lir_memory_operation_count: u32::try_from(lir.memory_operations())
            .expect("LIR Mem 数量适配 u32"),
        lir_safepoint_count: u32::try_from(lir.safepoints()).expect("LIR safepoint 数量适配 u32"),
        lir_fingerprint: lir.fingerprint(),
        optimization_revision: lir.optimization_revision(),
        poll_budget: lir.poll_budget(),
        poll_count: u32::try_from(lir.poll_count()).expect("poll 数量适配 u32"),
        poll_free_leaf_count: u32::try_from(lir.poll_free_leaf_count())
            .expect("poll-free 叶数量适配 u32"),
        poll_summary_fingerprint: lir.poll_summary_fingerprint(),
        raw_size_class_count: raw.class_count(),
        raw_shard_count: raw.shard_count(),
        raw_batch_max_items: raw.batch_limits().items,
        raw_batch_soft_bytes: raw.batch_limits().batch_soft_bytes,
        raw_message_node_capacity: raw.message_node_capacity(),
        raw_model_fingerprint: raw.fingerprint(),
        coroutine_runtime: raw.coroutine().clone(),
        resource_cell_header_bytes: raw.resources().header.header_bytes,
        resource_class_count: raw.resource_class_count(),
        resource_kind_count: raw.resource_kind_count(),
        release_descriptor_count: raw.resources().release.fields.len() as u32,
        resource_sites: raw.resource_demand().resource_sites,
        release_sites: raw.resource_demand().release_sites,
        platform_profile: raw.platform().profile().to_owned(),
        platform_op_count: raw.platform().op_count(),
        platform_range_class_count: raw.platform().class_count(),
        platform_contract_fingerprint: *blake3::Hasher::new_derive_key("gugu-platform-range-v1")
            .update(&raw.platform().canonical_bytes())
            .finalize()
            .as_bytes(),
        platform_demand: *raw.platform_demand(),
        ledger_category_count: raw.ledger_categories().len() as u32,
    })
}
