//! x86_64 form 表数据。
//!
//! 操作数按编码位置书写：第一个操作数占据 ModRM.r/m 位（或 `+r` 位），第二个寄存器
//! 操作数占据 ModRM.reg 位，立即数与 `cl` 是修饰操作数。`r,r/m` 与 `r/m,r` 方向由
//! opcode 区分，因此 operands 相同的两条 form 具有不同 opcode 与访问语义。

use super::reg::{Clobbers, Gpr};
use super::table::{
    Access::{Address, Read, ReadWrite, Write},
    Form,
    ImmKind::{Ib, Id, Io, Iw},
    Map::{ThreeByte3A, ThreeByte38, TwoByte, Vex},
    OperandKind::{
        Cl, Imm8, Imm16, Imm32, Imm64, Mem, R8, R16, R32, R64, Rel8, Rel32, Rm8, Rm16, Rm32, Rm64,
        Xmm, XmmRm,
    },
    POLL_COST_UNIT,
    Prefix::{OperandSize66, RepF2, RepF3},
};
use crate::target::CpuFeature;

/// 单操作数 `mul`/`imul`/`div`/`idiv` 隐式破坏 `rdx:rax`。
const RDX_RAX: Clobbers = Clobbers::gpr(Gpr::Rax).union(Clobbers::gpr(Gpr::Rdx));
/// `cdq`/`cqo` 隐式破坏 `rdx`。
const RDX: Clobbers = Clobbers::gpr(Gpr::Rdx);

/// 全部登记的 form；顺序即 [`super::table::FormId`] 编号。
#[rustfmt::skip]
pub(crate) const FORMS: &[Form] = &[
    // ---------------------------------------------------------------- 数据搬运
    Form::new("mov", &[Rm8, R8], &[Write, Read], 0x88, POLL_COST_UNIT),
    Form::new("mov", &[Rm16, R16], &[Write, Read], 0x89, POLL_COST_UNIT).prefix(OperandSize66),
    Form::new("mov", &[Rm32, R32], &[Write, Read], 0x89, POLL_COST_UNIT),
    Form::new("mov", &[Rm64, R64], &[Write, Read], 0x89, POLL_COST_UNIT).rex_w(),
    Form::new("mov", &[Rm8, R8], &[Read, Write], 0x8A, POLL_COST_UNIT),
    Form::new("mov", &[Rm16, R16], &[Read, Write], 0x8B, POLL_COST_UNIT).prefix(OperandSize66),
    Form::new("mov", &[Rm32, R32], &[Read, Write], 0x8B, POLL_COST_UNIT),
    Form::new("mov", &[Rm64, R64], &[Read, Write], 0x8B, POLL_COST_UNIT).rex_w(),
    Form::new("mov", &[R32, Imm32], &[Write, Read], 0xB8, POLL_COST_UNIT).reg_in_opcode().imm(Id),
    Form::new("mov", &[R64, Imm64], &[Write, Read], 0xB8, POLL_COST_UNIT).reg_in_opcode().rex_w().imm(Io),
    Form::new("mov", &[R64, Imm32], &[Write, Read], 0xC7, POLL_COST_UNIT).ext(0).rex_w().imm(Id),
    Form::new("mov", &[Rm32, Imm32], &[Write, Read], 0xC7, POLL_COST_UNIT).ext(0).imm(Id),
    Form::new("mov", &[Rm64, Imm32], &[Write, Read], 0xC7, POLL_COST_UNIT).ext(0).rex_w().imm(Id),
    Form::new("mov", &[Rm8, Imm8], &[Write, Read], 0xC6, POLL_COST_UNIT).ext(0).imm(Ib),
    Form::new("mov", &[Rm16, Imm16], &[Write, Read], 0xC7, POLL_COST_UNIT).ext(0).prefix(OperandSize66).imm(Iw),
    Form::new("movzx", &[Rm8, R32], &[Read, Write], 0xB6, POLL_COST_UNIT).map(TwoByte),
    Form::new("movzx", &[Rm8, R64], &[Read, Write], 0xB6, POLL_COST_UNIT).map(TwoByte).rex_w(),
    Form::new("movzx", &[Rm16, R32], &[Read, Write], 0xB7, POLL_COST_UNIT).map(TwoByte),
    Form::new("movzx", &[Rm16, R64], &[Read, Write], 0xB7, POLL_COST_UNIT).map(TwoByte).rex_w(),
    Form::new("movsx", &[Rm8, R32], &[Read, Write], 0xBE, POLL_COST_UNIT).map(TwoByte),
    Form::new("movsx", &[Rm8, R64], &[Read, Write], 0xBE, POLL_COST_UNIT).map(TwoByte).rex_w(),
    Form::new("movsx", &[Rm16, R32], &[Read, Write], 0xBF, POLL_COST_UNIT).map(TwoByte),
    Form::new("movsx", &[Rm16, R64], &[Read, Write], 0xBF, POLL_COST_UNIT).map(TwoByte).rex_w(),
    Form::new("movsxd", &[Rm32, R64], &[Read, Write], 0x63, POLL_COST_UNIT).rex_w(),
    Form::new("lea", &[Mem, R64], &[Address, Write], 0x8D, POLL_COST_UNIT).rex_w(),
    Form::new("xchg", &[Rm8, R8], &[ReadWrite, ReadWrite], 0x86, POLL_COST_UNIT),
    Form::new("xchg", &[Rm16, R16], &[ReadWrite, ReadWrite], 0x87, POLL_COST_UNIT).prefix(OperandSize66),
    Form::new("xchg", &[Rm32, R32], &[ReadWrite, ReadWrite], 0x87, POLL_COST_UNIT),
    Form::new("xchg", &[Rm64, R64], &[ReadWrite, ReadWrite], 0x87, POLL_COST_UNIT).rex_w(),
    Form::new("btc", &[Rm32, Imm8], &[ReadWrite, Read], 0xBA, POLL_COST_UNIT).map(TwoByte).ext(7).imm(Ib),
    Form::new("btc", &[Rm64, Imm8], &[ReadWrite, Read], 0xBA, POLL_COST_UNIT).map(TwoByte).ext(7).rex_w().imm(Ib),
    // 条件移动 0F 40..4F。
    Form::new("cmovo", &[Rm32, R32], &[Read, Write], 0x40, POLL_COST_UNIT).map(TwoByte),
    Form::new("cmovo", &[Rm64, R64], &[Read, Write], 0x40, POLL_COST_UNIT).map(TwoByte).rex_w(),
    Form::new("cmovno", &[Rm32, R32], &[Read, Write], 0x41, POLL_COST_UNIT).map(TwoByte),
    Form::new("cmovno", &[Rm64, R64], &[Read, Write], 0x41, POLL_COST_UNIT).map(TwoByte).rex_w(),
    Form::new("cmovb", &[Rm32, R32], &[Read, Write], 0x42, POLL_COST_UNIT).map(TwoByte),
    Form::new("cmovb", &[Rm64, R64], &[Read, Write], 0x42, POLL_COST_UNIT).map(TwoByte).rex_w(),
    Form::new("cmovae", &[Rm32, R32], &[Read, Write], 0x43, POLL_COST_UNIT).map(TwoByte),
    Form::new("cmovae", &[Rm64, R64], &[Read, Write], 0x43, POLL_COST_UNIT).map(TwoByte).rex_w(),
    Form::new("cmove", &[Rm32, R32], &[Read, Write], 0x44, POLL_COST_UNIT).map(TwoByte),
    Form::new("cmove", &[Rm64, R64], &[Read, Write], 0x44, POLL_COST_UNIT).map(TwoByte).rex_w(),
    Form::new("cmovne", &[Rm32, R32], &[Read, Write], 0x45, POLL_COST_UNIT).map(TwoByte),
    Form::new("cmovne", &[Rm64, R64], &[Read, Write], 0x45, POLL_COST_UNIT).map(TwoByte).rex_w(),
    Form::new("cmovbe", &[Rm32, R32], &[Read, Write], 0x46, POLL_COST_UNIT).map(TwoByte),
    Form::new("cmovbe", &[Rm64, R64], &[Read, Write], 0x46, POLL_COST_UNIT).map(TwoByte).rex_w(),
    Form::new("cmova", &[Rm32, R32], &[Read, Write], 0x47, POLL_COST_UNIT).map(TwoByte),
    Form::new("cmova", &[Rm64, R64], &[Read, Write], 0x47, POLL_COST_UNIT).map(TwoByte).rex_w(),
    Form::new("cmovs", &[Rm32, R32], &[Read, Write], 0x48, POLL_COST_UNIT).map(TwoByte),
    Form::new("cmovs", &[Rm64, R64], &[Read, Write], 0x48, POLL_COST_UNIT).map(TwoByte).rex_w(),
    Form::new("cmovns", &[Rm32, R32], &[Read, Write], 0x49, POLL_COST_UNIT).map(TwoByte),
    Form::new("cmovns", &[Rm64, R64], &[Read, Write], 0x49, POLL_COST_UNIT).map(TwoByte).rex_w(),
    Form::new("cmovp", &[Rm32, R32], &[Read, Write], 0x4A, POLL_COST_UNIT).map(TwoByte),
    Form::new("cmovp", &[Rm64, R64], &[Read, Write], 0x4A, POLL_COST_UNIT).map(TwoByte).rex_w(),
    Form::new("cmovnp", &[Rm32, R32], &[Read, Write], 0x4B, POLL_COST_UNIT).map(TwoByte),
    Form::new("cmovnp", &[Rm64, R64], &[Read, Write], 0x4B, POLL_COST_UNIT).map(TwoByte).rex_w(),
    Form::new("cmovl", &[Rm32, R32], &[Read, Write], 0x4C, POLL_COST_UNIT).map(TwoByte),
    Form::new("cmovl", &[Rm64, R64], &[Read, Write], 0x4C, POLL_COST_UNIT).map(TwoByte).rex_w(),
    Form::new("cmovge", &[Rm32, R32], &[Read, Write], 0x4D, POLL_COST_UNIT).map(TwoByte),
    Form::new("cmovge", &[Rm64, R64], &[Read, Write], 0x4D, POLL_COST_UNIT).map(TwoByte).rex_w(),
    Form::new("cmovle", &[Rm32, R32], &[Read, Write], 0x4E, POLL_COST_UNIT).map(TwoByte),
    Form::new("cmovle", &[Rm64, R64], &[Read, Write], 0x4E, POLL_COST_UNIT).map(TwoByte).rex_w(),
    Form::new("cmovg", &[Rm32, R32], &[Read, Write], 0x4F, POLL_COST_UNIT).map(TwoByte),
    Form::new("cmovg", &[Rm64, R64], &[Read, Write], 0x4F, POLL_COST_UNIT).map(TwoByte).rex_w(),
    // 条件置位 0F 90..9F。
    Form::new("seto", &[Rm8], &[Write], 0x90, POLL_COST_UNIT).map(TwoByte),
    Form::new("setno", &[Rm8], &[Write], 0x91, POLL_COST_UNIT).map(TwoByte),
    Form::new("setb", &[Rm8], &[Write], 0x92, POLL_COST_UNIT).map(TwoByte),
    Form::new("setae", &[Rm8], &[Write], 0x93, POLL_COST_UNIT).map(TwoByte),
    Form::new("sete", &[Rm8], &[Write], 0x94, POLL_COST_UNIT).map(TwoByte),
    Form::new("setne", &[Rm8], &[Write], 0x95, POLL_COST_UNIT).map(TwoByte),
    Form::new("setbe", &[Rm8], &[Write], 0x96, POLL_COST_UNIT).map(TwoByte),
    Form::new("seta", &[Rm8], &[Write], 0x97, POLL_COST_UNIT).map(TwoByte),
    Form::new("sets", &[Rm8], &[Write], 0x98, POLL_COST_UNIT).map(TwoByte),
    Form::new("setns", &[Rm8], &[Write], 0x99, POLL_COST_UNIT).map(TwoByte),
    Form::new("setp", &[Rm8], &[Write], 0x9A, POLL_COST_UNIT).map(TwoByte),
    Form::new("setnp", &[Rm8], &[Write], 0x9B, POLL_COST_UNIT).map(TwoByte),
    Form::new("setl", &[Rm8], &[Write], 0x9C, POLL_COST_UNIT).map(TwoByte),
    Form::new("setge", &[Rm8], &[Write], 0x9D, POLL_COST_UNIT).map(TwoByte),
    Form::new("setle", &[Rm8], &[Write], 0x9E, POLL_COST_UNIT).map(TwoByte),
    Form::new("setg", &[Rm8], &[Write], 0x9F, POLL_COST_UNIT).map(TwoByte),
    Form::new("movd", &[Rm32, Xmm], &[Read, Write], 0x6E, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("movq", &[Rm64, Xmm], &[Read, Write], 0x6E, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66).rex_w(),
    Form::new("movd", &[Rm32, Xmm], &[Write, Read], 0x7E, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("movq", &[Rm64, Xmm], &[Write, Read], 0x7E, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66).rex_w(),
    Form::new("movq", &[XmmRm, Xmm], &[Read, Write], 0x7E, POLL_COST_UNIT).map(TwoByte).prefix(RepF3),
    Form::new("movq", &[XmmRm, Xmm], &[Write, Read], 0xD6, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("movss", &[XmmRm, Xmm], &[Read, Write], 0x10, POLL_COST_UNIT).map(TwoByte).prefix(RepF3),
    Form::new("movss", &[XmmRm, Xmm], &[Write, Read], 0x11, POLL_COST_UNIT).map(TwoByte).prefix(RepF3),
    Form::new("movsd", &[XmmRm, Xmm], &[Read, Write], 0x10, POLL_COST_UNIT).map(TwoByte).prefix(RepF2),
    Form::new("movsd", &[XmmRm, Xmm], &[Write, Read], 0x11, POLL_COST_UNIT).map(TwoByte).prefix(RepF2),
    Form::new("movups", &[XmmRm, Xmm], &[Read, Write], 0x10, POLL_COST_UNIT).map(TwoByte),
    Form::new("movups", &[XmmRm, Xmm], &[Write, Read], 0x11, POLL_COST_UNIT).map(TwoByte),
    Form::new("movaps", &[XmmRm, Xmm], &[Read, Write], 0x28, POLL_COST_UNIT).map(TwoByte),
    Form::new("movaps", &[XmmRm, Xmm], &[Write, Read], 0x29, POLL_COST_UNIT).map(TwoByte),
    Form::new("movdqu", &[XmmRm, Xmm], &[Read, Write], 0x6F, POLL_COST_UNIT).map(TwoByte).prefix(RepF3),
    Form::new("movdqu", &[XmmRm, Xmm], &[Write, Read], 0x7F, POLL_COST_UNIT).map(TwoByte).prefix(RepF3),
    Form::new("movdqa", &[XmmRm, Xmm], &[Read, Write], 0x6F, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("movdqa", &[XmmRm, Xmm], &[Write, Read], 0x7F, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    // ---------------------------------------------------------------- 整数算术
    // add/sub/and/or/xor：r/m,r 与 r,r/m 的 8/16/32/64 宽度，r/m,imm32，r/m,imm8（含 16/32/64 与 8 位）。
    Form::new("add", &[Rm8, R8], &[ReadWrite, Read], 0x00, POLL_COST_UNIT).lock_allowed(),
    Form::new("add", &[Rm16, R16], &[ReadWrite, Read], 0x01, POLL_COST_UNIT).prefix(OperandSize66).lock_allowed(),
    Form::new("add", &[Rm32, R32], &[ReadWrite, Read], 0x01, POLL_COST_UNIT).lock_allowed(),
    Form::new("add", &[Rm64, R64], &[ReadWrite, Read], 0x01, POLL_COST_UNIT).rex_w().lock_allowed(),
    Form::new("add", &[Rm8, R8], &[Read, ReadWrite], 0x02, POLL_COST_UNIT),
    Form::new("add", &[Rm16, R16], &[Read, ReadWrite], 0x03, POLL_COST_UNIT).prefix(OperandSize66),
    Form::new("add", &[Rm32, R32], &[Read, ReadWrite], 0x03, POLL_COST_UNIT),
    Form::new("add", &[Rm64, R64], &[Read, ReadWrite], 0x03, POLL_COST_UNIT).rex_w(),
    Form::new("add", &[Rm8, Imm8], &[ReadWrite, Read], 0x80, POLL_COST_UNIT).ext(0).imm(Ib).lock_allowed(),
    Form::new("add", &[Rm16, Imm16], &[ReadWrite, Read], 0x81, POLL_COST_UNIT).ext(0).prefix(OperandSize66).imm(Iw).lock_allowed(),
    Form::new("add", &[Rm32, Imm32], &[ReadWrite, Read], 0x81, POLL_COST_UNIT).ext(0).imm(Id).lock_allowed(),
    Form::new("add", &[Rm64, Imm32], &[ReadWrite, Read], 0x81, POLL_COST_UNIT).ext(0).rex_w().imm(Id).lock_allowed(),
    Form::new("add", &[Rm16, Imm8], &[ReadWrite, Read], 0x83, POLL_COST_UNIT).ext(0).prefix(OperandSize66).imm(Ib).lock_allowed(),
    Form::new("add", &[Rm32, Imm8], &[ReadWrite, Read], 0x83, POLL_COST_UNIT).ext(0).imm(Ib).lock_allowed(),
    Form::new("add", &[Rm64, Imm8], &[ReadWrite, Read], 0x83, POLL_COST_UNIT).ext(0).rex_w().imm(Ib).lock_allowed(),
    Form::new("sub", &[Rm8, R8], &[ReadWrite, Read], 0x28, POLL_COST_UNIT).lock_allowed(),
    Form::new("sub", &[Rm16, R16], &[ReadWrite, Read], 0x29, POLL_COST_UNIT).prefix(OperandSize66).lock_allowed(),
    Form::new("sub", &[Rm32, R32], &[ReadWrite, Read], 0x29, POLL_COST_UNIT).lock_allowed(),
    Form::new("sub", &[Rm64, R64], &[ReadWrite, Read], 0x29, POLL_COST_UNIT).rex_w().lock_allowed(),
    Form::new("sub", &[Rm8, R8], &[Read, ReadWrite], 0x2A, POLL_COST_UNIT),
    Form::new("sub", &[Rm16, R16], &[Read, ReadWrite], 0x2B, POLL_COST_UNIT).prefix(OperandSize66),
    Form::new("sub", &[Rm32, R32], &[Read, ReadWrite], 0x2B, POLL_COST_UNIT),
    Form::new("sub", &[Rm64, R64], &[Read, ReadWrite], 0x2B, POLL_COST_UNIT).rex_w(),
    Form::new("sub", &[Rm8, Imm8], &[ReadWrite, Read], 0x80, POLL_COST_UNIT).ext(5).imm(Ib).lock_allowed(),
    Form::new("sub", &[Rm16, Imm16], &[ReadWrite, Read], 0x81, POLL_COST_UNIT).ext(5).prefix(OperandSize66).imm(Iw).lock_allowed(),
    Form::new("sub", &[Rm32, Imm32], &[ReadWrite, Read], 0x81, POLL_COST_UNIT).ext(5).imm(Id).lock_allowed(),
    Form::new("sub", &[Rm64, Imm32], &[ReadWrite, Read], 0x81, POLL_COST_UNIT).ext(5).rex_w().imm(Id).lock_allowed(),
    Form::new("sub", &[Rm16, Imm8], &[ReadWrite, Read], 0x83, POLL_COST_UNIT).ext(5).prefix(OperandSize66).imm(Ib).lock_allowed(),
    Form::new("sub", &[Rm32, Imm8], &[ReadWrite, Read], 0x83, POLL_COST_UNIT).ext(5).imm(Ib).lock_allowed(),
    Form::new("sub", &[Rm64, Imm8], &[ReadWrite, Read], 0x83, POLL_COST_UNIT).ext(5).rex_w().imm(Ib).lock_allowed(),
    Form::new("and", &[Rm8, R8], &[ReadWrite, Read], 0x20, POLL_COST_UNIT).lock_allowed(),
    Form::new("and", &[Rm16, R16], &[ReadWrite, Read], 0x21, POLL_COST_UNIT).prefix(OperandSize66).lock_allowed(),
    Form::new("and", &[Rm32, R32], &[ReadWrite, Read], 0x21, POLL_COST_UNIT).lock_allowed(),
    Form::new("and", &[Rm64, R64], &[ReadWrite, Read], 0x21, POLL_COST_UNIT).rex_w().lock_allowed(),
    Form::new("and", &[Rm8, R8], &[Read, ReadWrite], 0x22, POLL_COST_UNIT),
    Form::new("and", &[Rm16, R16], &[Read, ReadWrite], 0x23, POLL_COST_UNIT).prefix(OperandSize66),
    Form::new("and", &[Rm32, R32], &[Read, ReadWrite], 0x23, POLL_COST_UNIT),
    Form::new("and", &[Rm64, R64], &[Read, ReadWrite], 0x23, POLL_COST_UNIT).rex_w(),
    Form::new("and", &[Rm8, Imm8], &[ReadWrite, Read], 0x80, POLL_COST_UNIT).ext(4).imm(Ib).lock_allowed(),
    Form::new("and", &[Rm16, Imm16], &[ReadWrite, Read], 0x81, POLL_COST_UNIT).ext(4).prefix(OperandSize66).imm(Iw).lock_allowed(),
    Form::new("and", &[Rm32, Imm32], &[ReadWrite, Read], 0x81, POLL_COST_UNIT).ext(4).imm(Id).lock_allowed(),
    Form::new("and", &[Rm64, Imm32], &[ReadWrite, Read], 0x81, POLL_COST_UNIT).ext(4).rex_w().imm(Id).lock_allowed(),
    Form::new("and", &[Rm16, Imm8], &[ReadWrite, Read], 0x83, POLL_COST_UNIT).ext(4).prefix(OperandSize66).imm(Ib).lock_allowed(),
    Form::new("and", &[Rm32, Imm8], &[ReadWrite, Read], 0x83, POLL_COST_UNIT).ext(4).imm(Ib).lock_allowed(),
    Form::new("and", &[Rm64, Imm8], &[ReadWrite, Read], 0x83, POLL_COST_UNIT).ext(4).rex_w().imm(Ib).lock_allowed(),
    Form::new("or", &[Rm8, R8], &[ReadWrite, Read], 0x08, POLL_COST_UNIT).lock_allowed(),
    Form::new("or", &[Rm16, R16], &[ReadWrite, Read], 0x09, POLL_COST_UNIT).prefix(OperandSize66).lock_allowed(),
    Form::new("or", &[Rm32, R32], &[ReadWrite, Read], 0x09, POLL_COST_UNIT).lock_allowed(),
    Form::new("or", &[Rm64, R64], &[ReadWrite, Read], 0x09, POLL_COST_UNIT).rex_w().lock_allowed(),
    Form::new("or", &[Rm8, R8], &[Read, ReadWrite], 0x0A, POLL_COST_UNIT),
    Form::new("or", &[Rm16, R16], &[Read, ReadWrite], 0x0B, POLL_COST_UNIT).prefix(OperandSize66),
    Form::new("or", &[Rm32, R32], &[Read, ReadWrite], 0x0B, POLL_COST_UNIT),
    Form::new("or", &[Rm64, R64], &[Read, ReadWrite], 0x0B, POLL_COST_UNIT).rex_w(),
    Form::new("or", &[Rm8, Imm8], &[ReadWrite, Read], 0x80, POLL_COST_UNIT).ext(1).imm(Ib).lock_allowed(),
    Form::new("or", &[Rm16, Imm16], &[ReadWrite, Read], 0x81, POLL_COST_UNIT).ext(1).prefix(OperandSize66).imm(Iw).lock_allowed(),
    Form::new("or", &[Rm32, Imm32], &[ReadWrite, Read], 0x81, POLL_COST_UNIT).ext(1).imm(Id).lock_allowed(),
    Form::new("or", &[Rm64, Imm32], &[ReadWrite, Read], 0x81, POLL_COST_UNIT).ext(1).rex_w().imm(Id).lock_allowed(),
    Form::new("or", &[Rm16, Imm8], &[ReadWrite, Read], 0x83, POLL_COST_UNIT).ext(1).prefix(OperandSize66).imm(Ib).lock_allowed(),
    Form::new("or", &[Rm32, Imm8], &[ReadWrite, Read], 0x83, POLL_COST_UNIT).ext(1).imm(Ib).lock_allowed(),
    Form::new("or", &[Rm64, Imm8], &[ReadWrite, Read], 0x83, POLL_COST_UNIT).ext(1).rex_w().imm(Ib).lock_allowed(),
    Form::new("xor", &[Rm8, R8], &[ReadWrite, Read], 0x30, POLL_COST_UNIT).lock_allowed(),
    Form::new("xor", &[Rm16, R16], &[ReadWrite, Read], 0x31, POLL_COST_UNIT).prefix(OperandSize66).lock_allowed(),
    Form::new("xor", &[Rm32, R32], &[ReadWrite, Read], 0x31, POLL_COST_UNIT).lock_allowed(),
    Form::new("xor", &[Rm64, R64], &[ReadWrite, Read], 0x31, POLL_COST_UNIT).rex_w().lock_allowed(),
    Form::new("xor", &[Rm8, R8], &[Read, ReadWrite], 0x32, POLL_COST_UNIT),
    Form::new("xor", &[Rm16, R16], &[Read, ReadWrite], 0x33, POLL_COST_UNIT).prefix(OperandSize66),
    Form::new("xor", &[Rm32, R32], &[Read, ReadWrite], 0x33, POLL_COST_UNIT),
    Form::new("xor", &[Rm64, R64], &[Read, ReadWrite], 0x33, POLL_COST_UNIT).rex_w(),
    Form::new("xor", &[Rm8, Imm8], &[ReadWrite, Read], 0x80, POLL_COST_UNIT).ext(6).imm(Ib).lock_allowed(),
    Form::new("xor", &[Rm16, Imm16], &[ReadWrite, Read], 0x81, POLL_COST_UNIT).ext(6).prefix(OperandSize66).imm(Iw).lock_allowed(),
    Form::new("xor", &[Rm32, Imm32], &[ReadWrite, Read], 0x81, POLL_COST_UNIT).ext(6).imm(Id).lock_allowed(),
    Form::new("xor", &[Rm64, Imm32], &[ReadWrite, Read], 0x81, POLL_COST_UNIT).ext(6).rex_w().imm(Id).lock_allowed(),
    Form::new("xor", &[Rm16, Imm8], &[ReadWrite, Read], 0x83, POLL_COST_UNIT).ext(6).prefix(OperandSize66).imm(Ib).lock_allowed(),
    Form::new("xor", &[Rm32, Imm8], &[ReadWrite, Read], 0x83, POLL_COST_UNIT).ext(6).imm(Ib).lock_allowed(),
    Form::new("xor", &[Rm64, Imm8], &[ReadWrite, Read], 0x83, POLL_COST_UNIT).ext(6).rex_w().imm(Ib).lock_allowed(),
    Form::new("cmp", &[Rm8, R8], &[Read, Read], 0x38, POLL_COST_UNIT),
    Form::new("cmp", &[Rm16, R16], &[Read, Read], 0x39, POLL_COST_UNIT).prefix(OperandSize66),
    Form::new("cmp", &[Rm32, R32], &[Read, Read], 0x39, POLL_COST_UNIT),
    Form::new("cmp", &[Rm64, R64], &[Read, Read], 0x39, POLL_COST_UNIT).rex_w(),
    Form::new("cmp", &[Rm8, R8], &[Read, Read], 0x3A, POLL_COST_UNIT),
    Form::new("cmp", &[Rm16, R16], &[Read, Read], 0x3B, POLL_COST_UNIT).prefix(OperandSize66),
    Form::new("cmp", &[Rm32, R32], &[Read, Read], 0x3B, POLL_COST_UNIT),
    Form::new("cmp", &[Rm64, R64], &[Read, Read], 0x3B, POLL_COST_UNIT).rex_w(),
    Form::new("cmp", &[Rm8, Imm8], &[Read, Read], 0x80, POLL_COST_UNIT).ext(7).imm(Ib),
    Form::new("cmp", &[Rm16, Imm16], &[Read, Read], 0x81, POLL_COST_UNIT).ext(7).prefix(OperandSize66).imm(Iw),
    Form::new("cmp", &[Rm32, Imm32], &[Read, Read], 0x81, POLL_COST_UNIT).ext(7).imm(Id),
    Form::new("cmp", &[Rm64, Imm32], &[Read, Read], 0x81, POLL_COST_UNIT).ext(7).rex_w().imm(Id),
    Form::new("cmp", &[Rm16, Imm8], &[Read, Read], 0x83, POLL_COST_UNIT).ext(7).prefix(OperandSize66).imm(Ib),
    Form::new("cmp", &[Rm32, Imm8], &[Read, Read], 0x83, POLL_COST_UNIT).ext(7).imm(Ib),
    Form::new("cmp", &[Rm64, Imm8], &[Read, Read], 0x83, POLL_COST_UNIT).ext(7).rex_w().imm(Ib),
    // 带进位加减：只登记 16/32/64 的寄存器与 imm8 形式。
    Form::new("adc", &[Rm16, R16], &[ReadWrite, Read], 0x11, POLL_COST_UNIT).prefix(OperandSize66).lock_allowed(),
    Form::new("adc", &[Rm32, R32], &[ReadWrite, Read], 0x11, POLL_COST_UNIT).lock_allowed(),
    Form::new("adc", &[Rm64, R64], &[ReadWrite, Read], 0x11, POLL_COST_UNIT).rex_w().lock_allowed(),
    Form::new("adc", &[Rm16, R16], &[Read, ReadWrite], 0x13, POLL_COST_UNIT).prefix(OperandSize66),
    Form::new("adc", &[Rm32, R32], &[Read, ReadWrite], 0x13, POLL_COST_UNIT),
    Form::new("adc", &[Rm64, R64], &[Read, ReadWrite], 0x13, POLL_COST_UNIT).rex_w(),
    Form::new("adc", &[Rm16, Imm8], &[ReadWrite, Read], 0x83, POLL_COST_UNIT).ext(2).prefix(OperandSize66).imm(Ib).lock_allowed(),
    Form::new("adc", &[Rm32, Imm8], &[ReadWrite, Read], 0x83, POLL_COST_UNIT).ext(2).imm(Ib).lock_allowed(),
    Form::new("adc", &[Rm64, Imm8], &[ReadWrite, Read], 0x83, POLL_COST_UNIT).ext(2).rex_w().imm(Ib).lock_allowed(),
    Form::new("sbb", &[Rm16, R16], &[ReadWrite, Read], 0x19, POLL_COST_UNIT).prefix(OperandSize66).lock_allowed(),
    Form::new("sbb", &[Rm32, R32], &[ReadWrite, Read], 0x19, POLL_COST_UNIT).lock_allowed(),
    Form::new("sbb", &[Rm64, R64], &[ReadWrite, Read], 0x19, POLL_COST_UNIT).rex_w().lock_allowed(),
    Form::new("sbb", &[Rm16, R16], &[Read, ReadWrite], 0x1B, POLL_COST_UNIT).prefix(OperandSize66),
    Form::new("sbb", &[Rm32, R32], &[Read, ReadWrite], 0x1B, POLL_COST_UNIT),
    Form::new("sbb", &[Rm64, R64], &[Read, ReadWrite], 0x1B, POLL_COST_UNIT).rex_w(),
    Form::new("sbb", &[Rm16, Imm8], &[ReadWrite, Read], 0x83, POLL_COST_UNIT).ext(3).prefix(OperandSize66).imm(Ib).lock_allowed(),
    Form::new("sbb", &[Rm32, Imm8], &[ReadWrite, Read], 0x83, POLL_COST_UNIT).ext(3).imm(Ib).lock_allowed(),
    Form::new("sbb", &[Rm64, Imm8], &[ReadWrite, Read], 0x83, POLL_COST_UNIT).ext(3).rex_w().imm(Ib).lock_allowed(),
    Form::new("neg", &[Rm8], &[ReadWrite], 0xF6, POLL_COST_UNIT).ext(3),
    Form::new("neg", &[Rm16], &[ReadWrite], 0xF7, POLL_COST_UNIT).ext(3).prefix(OperandSize66),
    Form::new("neg", &[Rm32], &[ReadWrite], 0xF7, POLL_COST_UNIT).ext(3),
    Form::new("neg", &[Rm64], &[ReadWrite], 0xF7, POLL_COST_UNIT).ext(3).rex_w(),
    Form::new("not", &[Rm8], &[ReadWrite], 0xF6, POLL_COST_UNIT).ext(2),
    Form::new("not", &[Rm16], &[ReadWrite], 0xF7, POLL_COST_UNIT).ext(2).prefix(OperandSize66),
    Form::new("not", &[Rm32], &[ReadWrite], 0xF7, POLL_COST_UNIT).ext(2),
    Form::new("not", &[Rm64], &[ReadWrite], 0xF7, POLL_COST_UNIT).ext(2).rex_w(),
    Form::new("imul", &[Rm16, R16], &[Read, Write], 0xAF, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("imul", &[Rm32, R32], &[Read, Write], 0xAF, POLL_COST_UNIT).map(TwoByte),
    Form::new("imul", &[Rm64, R64], &[Read, Write], 0xAF, POLL_COST_UNIT).map(TwoByte).rex_w(),
    Form::new("imul", &[Rm16, R16, Imm8], &[Read, Write, Read], 0x6B, POLL_COST_UNIT).prefix(OperandSize66).imm(Ib),
    Form::new("imul", &[Rm32, R32, Imm8], &[Read, Write, Read], 0x6B, POLL_COST_UNIT).imm(Ib),
    Form::new("imul", &[Rm64, R64, Imm8], &[Read, Write, Read], 0x6B, POLL_COST_UNIT).rex_w().imm(Ib),
    Form::new("imul", &[Rm16, R16, Imm32], &[Read, Write, Read], 0x69, POLL_COST_UNIT).prefix(OperandSize66).imm(Id),
    Form::new("imul", &[Rm32, R32, Imm32], &[Read, Write, Read], 0x69, POLL_COST_UNIT).imm(Id),
    Form::new("imul", &[Rm64, R64, Imm32], &[Read, Write, Read], 0x69, POLL_COST_UNIT).rex_w().imm(Id),
    Form::new("imul", &[Rm16], &[Read], 0xF7, POLL_COST_UNIT).ext(5).prefix(OperandSize66).clobbers(RDX_RAX),
    Form::new("imul", &[Rm32], &[Read], 0xF7, POLL_COST_UNIT).ext(5).clobbers(RDX_RAX),
    Form::new("imul", &[Rm64], &[Read], 0xF7, POLL_COST_UNIT).ext(5).rex_w().clobbers(RDX_RAX),
    Form::new("mul", &[Rm16], &[Read], 0xF7, POLL_COST_UNIT).ext(4).prefix(OperandSize66).clobbers(RDX_RAX),
    Form::new("mul", &[Rm32], &[Read], 0xF7, POLL_COST_UNIT).ext(4).clobbers(RDX_RAX),
    Form::new("mul", &[Rm64], &[Read], 0xF7, POLL_COST_UNIT).ext(4).rex_w().clobbers(RDX_RAX),
    Form::new("idiv", &[Rm16], &[Read], 0xF7, POLL_COST_UNIT).ext(7).prefix(OperandSize66).clobbers(RDX_RAX),
    Form::new("idiv", &[Rm32], &[Read], 0xF7, POLL_COST_UNIT).ext(7).clobbers(RDX_RAX),
    Form::new("idiv", &[Rm64], &[Read], 0xF7, POLL_COST_UNIT).ext(7).rex_w().clobbers(RDX_RAX),
    Form::new("div", &[Rm16], &[Read], 0xF7, POLL_COST_UNIT).ext(6).prefix(OperandSize66).clobbers(RDX_RAX),
    Form::new("div", &[Rm32], &[Read], 0xF7, POLL_COST_UNIT).ext(6).clobbers(RDX_RAX),
    Form::new("div", &[Rm64], &[Read], 0xF7, POLL_COST_UNIT).ext(6).rex_w().clobbers(RDX_RAX),
    Form::new("cqo", &[], &[], 0x99, POLL_COST_UNIT).rex_w().clobbers(RDX),
    Form::new("cdq", &[], &[], 0x99, POLL_COST_UNIT).clobbers(RDX),
    Form::new("shl", &[Rm8], &[ReadWrite], 0xD0, POLL_COST_UNIT).ext(4),
    Form::new("shl", &[Rm16], &[ReadWrite], 0xD1, POLL_COST_UNIT).ext(4).prefix(OperandSize66),
    Form::new("shl", &[Rm32], &[ReadWrite], 0xD1, POLL_COST_UNIT).ext(4),
    Form::new("shl", &[Rm64], &[ReadWrite], 0xD1, POLL_COST_UNIT).ext(4).rex_w(),
    Form::new("shl", &[Rm8, Cl], &[ReadWrite, Read], 0xD2, POLL_COST_UNIT).ext(4),
    Form::new("shl", &[Rm16, Cl], &[ReadWrite, Read], 0xD3, POLL_COST_UNIT).ext(4).prefix(OperandSize66),
    Form::new("shl", &[Rm32, Cl], &[ReadWrite, Read], 0xD3, POLL_COST_UNIT).ext(4),
    Form::new("shl", &[Rm64, Cl], &[ReadWrite, Read], 0xD3, POLL_COST_UNIT).ext(4).rex_w(),
    Form::new("shl", &[Rm8, Imm8], &[ReadWrite, Read], 0xC0, POLL_COST_UNIT).ext(4).imm(Ib),
    Form::new("shl", &[Rm16, Imm8], &[ReadWrite, Read], 0xC1, POLL_COST_UNIT).ext(4).prefix(OperandSize66).imm(Ib),
    Form::new("shl", &[Rm32, Imm8], &[ReadWrite, Read], 0xC1, POLL_COST_UNIT).ext(4).imm(Ib),
    Form::new("shl", &[Rm64, Imm8], &[ReadWrite, Read], 0xC1, POLL_COST_UNIT).ext(4).rex_w().imm(Ib),
    Form::new("shr", &[Rm8], &[ReadWrite], 0xD0, POLL_COST_UNIT).ext(5),
    Form::new("shr", &[Rm16], &[ReadWrite], 0xD1, POLL_COST_UNIT).ext(5).prefix(OperandSize66),
    Form::new("shr", &[Rm32], &[ReadWrite], 0xD1, POLL_COST_UNIT).ext(5),
    Form::new("shr", &[Rm64], &[ReadWrite], 0xD1, POLL_COST_UNIT).ext(5).rex_w(),
    Form::new("shr", &[Rm8, Cl], &[ReadWrite, Read], 0xD2, POLL_COST_UNIT).ext(5),
    Form::new("shr", &[Rm16, Cl], &[ReadWrite, Read], 0xD3, POLL_COST_UNIT).ext(5).prefix(OperandSize66),
    Form::new("shr", &[Rm32, Cl], &[ReadWrite, Read], 0xD3, POLL_COST_UNIT).ext(5),
    Form::new("shr", &[Rm64, Cl], &[ReadWrite, Read], 0xD3, POLL_COST_UNIT).ext(5).rex_w(),
    Form::new("shr", &[Rm8, Imm8], &[ReadWrite, Read], 0xC0, POLL_COST_UNIT).ext(5).imm(Ib),
    Form::new("shr", &[Rm16, Imm8], &[ReadWrite, Read], 0xC1, POLL_COST_UNIT).ext(5).prefix(OperandSize66).imm(Ib),
    Form::new("shr", &[Rm32, Imm8], &[ReadWrite, Read], 0xC1, POLL_COST_UNIT).ext(5).imm(Ib),
    Form::new("shr", &[Rm64, Imm8], &[ReadWrite, Read], 0xC1, POLL_COST_UNIT).ext(5).rex_w().imm(Ib),
    Form::new("sar", &[Rm8], &[ReadWrite], 0xD0, POLL_COST_UNIT).ext(7),
    Form::new("sar", &[Rm16], &[ReadWrite], 0xD1, POLL_COST_UNIT).ext(7).prefix(OperandSize66),
    Form::new("sar", &[Rm32], &[ReadWrite], 0xD1, POLL_COST_UNIT).ext(7),
    Form::new("sar", &[Rm64], &[ReadWrite], 0xD1, POLL_COST_UNIT).ext(7).rex_w(),
    Form::new("sar", &[Rm8, Cl], &[ReadWrite, Read], 0xD2, POLL_COST_UNIT).ext(7),
    Form::new("sar", &[Rm16, Cl], &[ReadWrite, Read], 0xD3, POLL_COST_UNIT).ext(7).prefix(OperandSize66),
    Form::new("sar", &[Rm32, Cl], &[ReadWrite, Read], 0xD3, POLL_COST_UNIT).ext(7),
    Form::new("sar", &[Rm64, Cl], &[ReadWrite, Read], 0xD3, POLL_COST_UNIT).ext(7).rex_w(),
    Form::new("sar", &[Rm8, Imm8], &[ReadWrite, Read], 0xC0, POLL_COST_UNIT).ext(7).imm(Ib),
    Form::new("sar", &[Rm16, Imm8], &[ReadWrite, Read], 0xC1, POLL_COST_UNIT).ext(7).prefix(OperandSize66).imm(Ib),
    Form::new("sar", &[Rm32, Imm8], &[ReadWrite, Read], 0xC1, POLL_COST_UNIT).ext(7).imm(Ib),
    Form::new("sar", &[Rm64, Imm8], &[ReadWrite, Read], 0xC1, POLL_COST_UNIT).ext(7).rex_w().imm(Ib),
    Form::new("test", &[Rm8, R8], &[Read, Read], 0x84, POLL_COST_UNIT),
    Form::new("test", &[Rm16, R16], &[Read, Read], 0x85, POLL_COST_UNIT).prefix(OperandSize66),
    Form::new("test", &[Rm32, R32], &[Read, Read], 0x85, POLL_COST_UNIT),
    Form::new("test", &[Rm64, R64], &[Read, Read], 0x85, POLL_COST_UNIT).rex_w(),
    Form::new("test", &[Rm8, Imm8], &[Read, Read], 0xF6, POLL_COST_UNIT).ext(0).imm(Ib),
    Form::new("test", &[Rm16, Imm16], &[Read, Read], 0xF7, POLL_COST_UNIT).ext(0).prefix(OperandSize66).imm(Iw),
    Form::new("test", &[Rm32, Imm32], &[Read, Read], 0xF7, POLL_COST_UNIT).ext(0).imm(Id),
    Form::new("test", &[Rm64, Imm32], &[Read, Read], 0xF7, POLL_COST_UNIT).ext(0).rex_w().imm(Id),
    Form::new("inc", &[Rm16], &[ReadWrite], 0xFF, POLL_COST_UNIT).ext(0).prefix(OperandSize66).lock_allowed(),
    Form::new("inc", &[Rm32], &[ReadWrite], 0xFF, POLL_COST_UNIT).ext(0).lock_allowed(),
    Form::new("inc", &[Rm64], &[ReadWrite], 0xFF, POLL_COST_UNIT).ext(0).rex_w().lock_allowed(),
    // ---------------------------------------------------------------- 控制流
    Form::new("jmp", &[Rel32], &[Read], 0xE9, POLL_COST_UNIT),
    Form::new("jmp", &[Rel8], &[Read], 0xEB, POLL_COST_UNIT),
    Form::new("jo", &[Rel32], &[Read], 0x80, POLL_COST_UNIT).map(TwoByte),
    Form::new("jo", &[Rel8], &[Read], 0x70, POLL_COST_UNIT),
    Form::new("jno", &[Rel32], &[Read], 0x81, POLL_COST_UNIT).map(TwoByte),
    Form::new("jno", &[Rel8], &[Read], 0x71, POLL_COST_UNIT),
    Form::new("jb", &[Rel32], &[Read], 0x82, POLL_COST_UNIT).map(TwoByte),
    Form::new("jb", &[Rel8], &[Read], 0x72, POLL_COST_UNIT),
    Form::new("jae", &[Rel32], &[Read], 0x83, POLL_COST_UNIT).map(TwoByte),
    Form::new("jae", &[Rel8], &[Read], 0x73, POLL_COST_UNIT),
    Form::new("je", &[Rel32], &[Read], 0x84, POLL_COST_UNIT).map(TwoByte),
    Form::new("je", &[Rel8], &[Read], 0x74, POLL_COST_UNIT),
    Form::new("jne", &[Rel32], &[Read], 0x85, POLL_COST_UNIT).map(TwoByte),
    Form::new("jne", &[Rel8], &[Read], 0x75, POLL_COST_UNIT),
    Form::new("jbe", &[Rel32], &[Read], 0x86, POLL_COST_UNIT).map(TwoByte),
    Form::new("jbe", &[Rel8], &[Read], 0x76, POLL_COST_UNIT),
    Form::new("ja", &[Rel32], &[Read], 0x87, POLL_COST_UNIT).map(TwoByte),
    Form::new("ja", &[Rel8], &[Read], 0x77, POLL_COST_UNIT),
    Form::new("js", &[Rel32], &[Read], 0x88, POLL_COST_UNIT).map(TwoByte),
    Form::new("js", &[Rel8], &[Read], 0x78, POLL_COST_UNIT),
    Form::new("jns", &[Rel32], &[Read], 0x89, POLL_COST_UNIT).map(TwoByte),
    Form::new("jns", &[Rel8], &[Read], 0x79, POLL_COST_UNIT),
    Form::new("jp", &[Rel32], &[Read], 0x8A, POLL_COST_UNIT).map(TwoByte),
    Form::new("jp", &[Rel8], &[Read], 0x7A, POLL_COST_UNIT),
    Form::new("jnp", &[Rel32], &[Read], 0x8B, POLL_COST_UNIT).map(TwoByte),
    Form::new("jnp", &[Rel8], &[Read], 0x7B, POLL_COST_UNIT),
    Form::new("jl", &[Rel32], &[Read], 0x8C, POLL_COST_UNIT).map(TwoByte),
    Form::new("jl", &[Rel8], &[Read], 0x7C, POLL_COST_UNIT),
    Form::new("jge", &[Rel32], &[Read], 0x8D, POLL_COST_UNIT).map(TwoByte),
    Form::new("jge", &[Rel8], &[Read], 0x7D, POLL_COST_UNIT),
    Form::new("jle", &[Rel32], &[Read], 0x8E, POLL_COST_UNIT).map(TwoByte),
    Form::new("jle", &[Rel8], &[Read], 0x7E, POLL_COST_UNIT),
    Form::new("jg", &[Rel32], &[Read], 0x8F, POLL_COST_UNIT).map(TwoByte),
    Form::new("jg", &[Rel8], &[Read], 0x7F, POLL_COST_UNIT),
    Form::new("call", &[Rel32], &[Read], 0xE8, POLL_COST_UNIT),
    Form::new("call", &[Rm64], &[Read], 0xFF, POLL_COST_UNIT).ext(2),
    Form::new("jmp", &[Rm64], &[Read], 0xFF, POLL_COST_UNIT).ext(4),
    Form::new("push", &[R64], &[Read], 0x50, POLL_COST_UNIT).reg_in_opcode(),
    Form::new("pop", &[R64], &[Write], 0x58, POLL_COST_UNIT).reg_in_opcode(),
    Form::new("ret", &[], &[], 0xC3, POLL_COST_UNIT),
    Form::new("nop", &[], &[], 0x90, POLL_COST_UNIT),
    Form::new("ud2", &[], &[], 0x0B, POLL_COST_UNIT).map(TwoByte),
    Form::new("pause", &[], &[], 0x90, POLL_COST_UNIT).prefix(RepF3),
    // ---------------------------------------------------------------- 原子
    Form::new("cmpxchg", &[Rm8, R8], &[ReadWrite, Read], 0xB0, POLL_COST_UNIT).map(TwoByte).lock_allowed(),
    Form::new("cmpxchg", &[Rm16, R16], &[ReadWrite, Read], 0xB1, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66).lock_allowed(),
    Form::new("cmpxchg", &[Rm32, R32], &[ReadWrite, Read], 0xB1, POLL_COST_UNIT).map(TwoByte).lock_allowed(),
    Form::new("cmpxchg", &[Rm64, R64], &[ReadWrite, Read], 0xB1, POLL_COST_UNIT).map(TwoByte).rex_w().lock_allowed(),
    Form::new("xadd", &[Rm8, R8], &[ReadWrite, Read], 0xC0, POLL_COST_UNIT).map(TwoByte).lock_allowed(),
    Form::new("xadd", &[Rm16, R16], &[ReadWrite, Read], 0xC1, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66).lock_allowed(),
    Form::new("xadd", &[Rm32, R32], &[ReadWrite, Read], 0xC1, POLL_COST_UNIT).map(TwoByte).lock_allowed(),
    Form::new("xadd", &[Rm64, R64], &[ReadWrite, Read], 0xC1, POLL_COST_UNIT).map(TwoByte).rex_w().lock_allowed(),
    Form::new("mfence", &[], &[], 0xAE, POLL_COST_UNIT).map(TwoByte).fixed_modrm(0xF0),
    Form::new("lfence", &[], &[], 0xAE, POLL_COST_UNIT).map(TwoByte).fixed_modrm(0xE8),
    Form::new("sfence", &[], &[], 0xAE, POLL_COST_UNIT).map(TwoByte).fixed_modrm(0xF8),
    // ---------------------------------------------------------------- SSE 浮点
    Form::new("addss", &[XmmRm, Xmm], &[Read, ReadWrite], 0x58, POLL_COST_UNIT).map(TwoByte).prefix(RepF3),
    Form::new("addsd", &[XmmRm, Xmm], &[Read, ReadWrite], 0x58, POLL_COST_UNIT).map(TwoByte).prefix(RepF2),
    Form::new("addps", &[XmmRm, Xmm], &[Read, ReadWrite], 0x58, POLL_COST_UNIT).map(TwoByte),
    Form::new("addpd", &[XmmRm, Xmm], &[Read, ReadWrite], 0x58, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("subss", &[XmmRm, Xmm], &[Read, ReadWrite], 0x5C, POLL_COST_UNIT).map(TwoByte).prefix(RepF3),
    Form::new("subsd", &[XmmRm, Xmm], &[Read, ReadWrite], 0x5C, POLL_COST_UNIT).map(TwoByte).prefix(RepF2),
    Form::new("subps", &[XmmRm, Xmm], &[Read, ReadWrite], 0x5C, POLL_COST_UNIT).map(TwoByte),
    Form::new("subpd", &[XmmRm, Xmm], &[Read, ReadWrite], 0x5C, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("mulss", &[XmmRm, Xmm], &[Read, ReadWrite], 0x59, POLL_COST_UNIT).map(TwoByte).prefix(RepF3),
    Form::new("mulsd", &[XmmRm, Xmm], &[Read, ReadWrite], 0x59, POLL_COST_UNIT).map(TwoByte).prefix(RepF2),
    Form::new("mulps", &[XmmRm, Xmm], &[Read, ReadWrite], 0x59, POLL_COST_UNIT).map(TwoByte),
    Form::new("mulpd", &[XmmRm, Xmm], &[Read, ReadWrite], 0x59, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("divss", &[XmmRm, Xmm], &[Read, ReadWrite], 0x5E, POLL_COST_UNIT).map(TwoByte).prefix(RepF3),
    Form::new("divsd", &[XmmRm, Xmm], &[Read, ReadWrite], 0x5E, POLL_COST_UNIT).map(TwoByte).prefix(RepF2),
    Form::new("ucomiss", &[XmmRm, Xmm], &[Read, Read], 0x2E, POLL_COST_UNIT).map(TwoByte),
    Form::new("ucomisd", &[XmmRm, Xmm], &[Read, Read], 0x2E, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("comiss", &[XmmRm, Xmm], &[Read, Read], 0x2F, POLL_COST_UNIT).map(TwoByte),
    Form::new("comisd", &[XmmRm, Xmm], &[Read, Read], 0x2F, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("cvtsi2ss", &[Rm32, Xmm], &[Read, ReadWrite], 0x2A, POLL_COST_UNIT).map(TwoByte).prefix(RepF3),
    Form::new("cvtsi2ss", &[Rm64, Xmm], &[Read, ReadWrite], 0x2A, POLL_COST_UNIT).map(TwoByte).prefix(RepF3).rex_w(),
    Form::new("cvtsi2sd", &[Rm32, Xmm], &[Read, ReadWrite], 0x2A, POLL_COST_UNIT).map(TwoByte).prefix(RepF2),
    Form::new("cvtsi2sd", &[Rm64, Xmm], &[Read, ReadWrite], 0x2A, POLL_COST_UNIT).map(TwoByte).prefix(RepF2).rex_w(),
    Form::new("cvttss2si", &[XmmRm, R32], &[Read, Write], 0x2C, POLL_COST_UNIT).map(TwoByte).prefix(RepF3),
    Form::new("cvttss2si", &[XmmRm, R64], &[Read, Write], 0x2C, POLL_COST_UNIT).map(TwoByte).prefix(RepF3).rex_w(),
    Form::new("cvttsd2si", &[XmmRm, R32], &[Read, Write], 0x2C, POLL_COST_UNIT).map(TwoByte).prefix(RepF2),
    Form::new("cvttsd2si", &[XmmRm, R64], &[Read, Write], 0x2C, POLL_COST_UNIT).map(TwoByte).prefix(RepF2).rex_w(),
    Form::new("cvtss2sd", &[XmmRm, Xmm], &[Read, Write], 0x5A, POLL_COST_UNIT).map(TwoByte).prefix(RepF3),
    Form::new("cvtsd2ss", &[XmmRm, Xmm], &[Read, Write], 0x5A, POLL_COST_UNIT).map(TwoByte).prefix(RepF2),
    Form::new("xorps", &[XmmRm, Xmm], &[Read, ReadWrite], 0x57, POLL_COST_UNIT).map(TwoByte),
    Form::new("xorpd", &[XmmRm, Xmm], &[Read, ReadWrite], 0x57, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("andps", &[XmmRm, Xmm], &[Read, ReadWrite], 0x54, POLL_COST_UNIT).map(TwoByte),
    Form::new("andpd", &[XmmRm, Xmm], &[Read, ReadWrite], 0x54, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("shufps", &[XmmRm, Xmm, Imm8], &[Read, ReadWrite, Read], 0xC6, POLL_COST_UNIT).map(TwoByte).imm(Ib),
    Form::new("shufpd", &[XmmRm, Xmm, Imm8], &[Read, ReadWrite, Read], 0xC6, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66).imm(Ib),
    Form::new("unpcklps", &[XmmRm, Xmm], &[Read, ReadWrite], 0x14, POLL_COST_UNIT).map(TwoByte),
    Form::new("unpckhps", &[XmmRm, Xmm], &[Read, ReadWrite], 0x15, POLL_COST_UNIT).map(TwoByte),
    Form::new("unpcklpd", &[XmmRm, Xmm], &[Read, ReadWrite], 0x14, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("unpckhpd", &[XmmRm, Xmm], &[Read, ReadWrite], 0x15, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("movlhps", &[Xmm, Xmm], &[Read, ReadWrite], 0x16, POLL_COST_UNIT).map(TwoByte),
    Form::new("movhlps", &[Xmm, Xmm], &[Read, ReadWrite], 0x12, POLL_COST_UNIT).map(TwoByte),
    Form::new("cmpps", &[XmmRm, Xmm, Imm8], &[Read, ReadWrite, Read], 0xC2, POLL_COST_UNIT).map(TwoByte).imm(Ib),
    Form::new("cmppd", &[XmmRm, Xmm, Imm8], &[Read, ReadWrite, Read], 0xC2, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66).imm(Ib),
    // ---------------------------------------------------------------- SSE 整型向量
    // SSE2 整型向量的形式都带 66 前缀；缺前缀会落到 MMX 寄存器上。
    Form::new("paddb", &[XmmRm, Xmm], &[Read, ReadWrite], 0xFC, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("paddw", &[XmmRm, Xmm], &[Read, ReadWrite], 0xFD, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("paddd", &[XmmRm, Xmm], &[Read, ReadWrite], 0xFE, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("paddq", &[XmmRm, Xmm], &[Read, ReadWrite], 0xD4, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("psubb", &[XmmRm, Xmm], &[Read, ReadWrite], 0xF8, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("psubw", &[XmmRm, Xmm], &[Read, ReadWrite], 0xF9, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("psubd", &[XmmRm, Xmm], &[Read, ReadWrite], 0xFA, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("psubq", &[XmmRm, Xmm], &[Read, ReadWrite], 0xFB, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("pmullw", &[XmmRm, Xmm], &[Read, ReadWrite], 0xD5, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("pmulhw", &[XmmRm, Xmm], &[Read, ReadWrite], 0xE5, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("pmulhuw", &[XmmRm, Xmm], &[Read, ReadWrite], 0xE4, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("pmuludq", &[XmmRm, Xmm], &[Read, ReadWrite], 0xF4, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("pmaddwd", &[XmmRm, Xmm], &[Read, ReadWrite], 0xF5, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("psadbw", &[XmmRm, Xmm], &[Read, ReadWrite], 0xF6, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("pand", &[XmmRm, Xmm], &[Read, ReadWrite], 0xDB, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("pandn", &[XmmRm, Xmm], &[Read, ReadWrite], 0xDF, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("por", &[XmmRm, Xmm], &[Read, ReadWrite], 0xEB, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("pxor", &[XmmRm, Xmm], &[Read, ReadWrite], 0xEF, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("pcmpeqb", &[XmmRm, Xmm], &[Read, ReadWrite], 0x74, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("pcmpeqw", &[XmmRm, Xmm], &[Read, ReadWrite], 0x75, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("pcmpeqd", &[XmmRm, Xmm], &[Read, ReadWrite], 0x76, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("pcmpgtb", &[XmmRm, Xmm], &[Read, ReadWrite], 0x64, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("pcmpgtw", &[XmmRm, Xmm], &[Read, ReadWrite], 0x65, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("pcmpgtd", &[XmmRm, Xmm], &[Read, ReadWrite], 0x66, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("punpcklbw", &[XmmRm, Xmm], &[Read, ReadWrite], 0x60, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("punpcklwd", &[XmmRm, Xmm], &[Read, ReadWrite], 0x61, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("punpckldq", &[XmmRm, Xmm], &[Read, ReadWrite], 0x62, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("punpcklqdq", &[XmmRm, Xmm], &[Read, ReadWrite], 0x6C, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("punpckhbw", &[XmmRm, Xmm], &[Read, ReadWrite], 0x68, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("punpckhwd", &[XmmRm, Xmm], &[Read, ReadWrite], 0x69, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("punpckhdq", &[XmmRm, Xmm], &[Read, ReadWrite], 0x6A, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("punpckhqdq", &[XmmRm, Xmm], &[Read, ReadWrite], 0x6D, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66),
    Form::new("pshufd", &[XmmRm, Xmm, Imm8], &[Read, Write, Read], 0x70, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66).imm(Ib),
    Form::new("pshuflw", &[XmmRm, Xmm, Imm8], &[Read, Write, Read], 0x70, POLL_COST_UNIT).map(TwoByte).prefix(RepF2).imm(Ib),
    Form::new("pshufhw", &[XmmRm, Xmm, Imm8], &[Read, Write, Read], 0x70, POLL_COST_UNIT).map(TwoByte).prefix(RepF3).imm(Ib),
    Form::new("psllw", &[Xmm, Imm8], &[ReadWrite, Read], 0x71, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66).ext(6).imm(Ib),
    Form::new("pslld", &[Xmm, Imm8], &[ReadWrite, Read], 0x72, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66).ext(6).imm(Ib),
    Form::new("psllq", &[Xmm, Imm8], &[ReadWrite, Read], 0x73, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66).ext(6).imm(Ib),
    Form::new("psrlw", &[Xmm, Imm8], &[ReadWrite, Read], 0x71, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66).ext(2).imm(Ib),
    Form::new("psrld", &[Xmm, Imm8], &[ReadWrite, Read], 0x72, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66).ext(2).imm(Ib),
    Form::new("psrlq", &[Xmm, Imm8], &[ReadWrite, Read], 0x73, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66).ext(2).imm(Ib),
    Form::new("psraw", &[Xmm, Imm8], &[ReadWrite, Read], 0x71, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66).ext(4).imm(Ib),
    Form::new("psrad", &[Xmm, Imm8], &[ReadWrite, Read], 0x72, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66).ext(4).imm(Ib),
    Form::new("pslldq", &[Xmm, Imm8], &[ReadWrite, Read], 0x73, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66).ext(7).imm(Ib),
    Form::new("psrldq", &[Xmm, Imm8], &[ReadWrite, Read], 0x73, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66).ext(3).imm(Ib),
    Form::new("pextrw", &[R32, Xmm, Imm8], &[Write, Read, Read], 0xC5, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66).imm(Ib),
    Form::new("insrw", &[R32, Xmm, Imm8], &[Read, ReadWrite, Read], 0xC4, POLL_COST_UNIT).map(TwoByte).prefix(OperandSize66).imm(Ib),
    // ---------------------------------------------------------------- 超出 x86-64-v1 的登记形式
    Form::new("pshufb", &[XmmRm, Xmm], &[Read, ReadWrite], 0x00, POLL_COST_UNIT).map(ThreeByte38).prefix(OperandSize66).feature(CpuFeature::Ssse3),
    Form::new("pmulld", &[XmmRm, Xmm], &[Read, ReadWrite], 0x40, POLL_COST_UNIT).map(ThreeByte38).prefix(OperandSize66).feature(CpuFeature::Sse41),
    Form::new("pextrd", &[Rm32, Xmm, Imm8], &[Write, Read, Read], 0x16, POLL_COST_UNIT).map(ThreeByte3A).prefix(OperandSize66).feature(CpuFeature::Sse41).imm(Ib),
    Form::new("pinsrd", &[Rm32, Xmm, Imm8], &[Read, ReadWrite, Read], 0x22, POLL_COST_UNIT).map(ThreeByte3A).prefix(OperandSize66).feature(CpuFeature::Sse41).imm(Ib),
    Form::new("vaddps", &[Xmm, Xmm, XmmRm], &[Write, Read, Read], 0x58, POLL_COST_UNIT).map(Vex).feature(CpuFeature::Avx),
];
